; MAKE SURE THIS IS SET CORRECTLY
;
; install_dir:
;   location kovaaks is installed
;   steam > kovaaks > properties > installed files > browse
;
; replace_folders:
;   true: hides default themes, sounds, and crosshairs because they SUCK
;   false: recommended if you have already added to these folders
;
; palette.ini:
;   sets ui colors
;   set to "current" to leave unchanged
;
; included palette.ini's: 
; - Viscose
; - MattyOW
;
; some included themes: 
; - clover-alternate (my recommendation)
; - clover-alternate-oled (if you have oled)
; - aech-new
; - emopalace edit (darker theme)
;
; make sure to set dpi below
; only cm/360 supported
; only overwatch fov supported
;
;
; ------------------------------------------------

[internal]
replace_folders = true
palette.ini = viscose

[Main]
visual_theme = clover-alternate
override_scenario_visuals = true
sensitivity = 40
dpi = 1600
fov = 103
crosshair = lmbsmolplus

[Weapons]
disable_weapon_model = true

[Sound]
hit_sound = wood-tap-click
hit_sound_cooldown = 0.06
kill_confirmed = none
spawn = 119415__joedeshon__rocker-switch

[Misc]
show_game_version = true
challenge_results_graph_history = 100

[skip]
skip_main = false
skip_hud = true
skip_hud_elements = false
skip_keybinds = false
skip_sounds = false
skip_video = false
skip_visuals = false
skip_weapons = false
skip_misc = false
