; Make sure to read instructions on github
; https://github.com/MistMissed/KovaaKsSaneDefaults#
; ------------------------------------------------

[internal]
replace_folders = true
palette.ini = viscose

[Main]
visual_theme = clover-alternate
override_scenario_visuals = true
sensitivity = 40
dpi = 1600
fov = 103
crosshair = lmbsmolplus

[Weapons]
disable_weapon_model = true

[Sound]
hit_sound = wood-tap-click
hit_sound_cooldown = 0.06
kill_confirmed = none
spawn = 119415__joedeshon__rocker-switch

[Misc]
show_game_version = true
challenge_results_graph_history = 100

[skip]
skip_main = false
skip_hud = true
skip_hud_elements = false
skip_keybinds = false
skip_sounds = false
skip_video = false
skip_visuals = false
skip_weapons = false
skip_misc = false
