; Make sure to read instructions on github
; https://github.com/MistMissed/KovaaKsSaneDefaults#

[Internal]
replace_folders = true
palette.ini = viscose

[Main]
visual_theme = clover-alternate
override_scenario_visuals = true
sensitivity = 40
dpi = 1600
fov = 103
crosshair = lmbsmolplus

[Weapons]
disable_weapon_model = true

[Sound]
hit_sound = wood-tap-click
hit_sound_cooldown = 0.06
spawn_sound = 119415__joedeshon__rocker-switch
kill_sound = none

[Misc]
show_game_version = true
challenge_results_graph_history = 100

